notifications:
  irc:
    channels: "chat.freenode.net#firedrake"
    skip_join: true
    on_success: change
    on_failure: always
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} | %{build_url}"

language: python
python:
  - "2.7"
  - "3.4"

before_install:
  - pip install pytest

install:
  - pip install .

script:
  - py.test test/
